-- Clock-sync arm ONLY (applied by apply_seed.py when BENCH_CLOCKSYNC=1).
--
-- Force memories.createdAt (on INSERT) and memories.updatedAt (on INSERT and on
-- UPDATE) onto the faked postmaster clock. Both columns are stamped CLIENT-side
-- by Prisma — createdAt via @default(now()), updatedAt via @updatedAt (which has
-- no DB default at all, so Prisma must send it on every INSERT and every UPDATE)
-- — and that value is generated by the Rust query engine whose CLOCK_REALTIME
-- read escapes libfaketime (vDSO). So both land at real wall-clock even though
-- the node process is preloaded and Postgres now() is faked. A trigger evaluated
-- by the (faked) postmaster overrides whatever the client sends, so both track
-- the dataset's logical session date like every other timestamp under
-- clock-sync. On UPDATE createdAt is left as stored — promotion must not rewrite
-- a memory's original logical creation date.
--
-- Why createdAt matters: the session-lifecycle scheduler's findStaleSessions
-- compares MAX(createdAt) < now() - SESSION_INACTIVITY_THRESHOLD_MS. With
-- createdAt at real-2026 and now() faked to the session year, every SESSION row
-- looks years in the future and never goes stale, so nothing is ever
-- promoted/summarized. The trigger closes that gap and also stamps the
-- server-written session-summary row (a later INSERT the adapter can't reach)
-- with logical time.
--
-- Why updatedAt matters: it is a ranking key and a recency anchor, not just
-- bookkeeping. fetchComparableMemories orders the dedup/conflict candidate
-- window by updatedAt DESC (engine/memory/write.ts:475), keyword search orders
-- by [importance DESC, updatedAt DESC] (api/memory.ts:389-391), and
-- getMemoryRecencyDate resolves eventDate || documentDate || updatedAt ||
-- createdAt (engine/memory/search.ts:58-66) — updatedAt is tried BEFORE
-- createdAt, so guarding only createdAt leaves the anchor broken. Promotion
-- UPDATEs the row (session-lifecycle.ts:147-158), which would restamp a
-- dataset-year memory to real-2026 and make it score as maximally recent for the
-- "recent/latest/previous" queries MemConflict probes.
--
-- Idempotent; scoped to the throwaway per-shard clock-sync cluster only.
CREATE OR REPLACE FUNCTION bench_force_created_at() RETURNS trigger AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    NEW."createdAt" := now();
  END IF;
  NEW."updatedAt" := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS bench_force_created_at ON memories;
CREATE TRIGGER bench_force_created_at
  BEFORE INSERT OR UPDATE ON memories
  FOR EACH ROW EXECUTE FUNCTION bench_force_created_at();
